-- Migration 072 — Tier 1 country installation history expansion
--
-- Compiled from:
--   • Wind onshore: WindEurope "Wind energy in Europe — Statistics & trends"
--     annual reports (2009-2025), GWEC Global Wind Reports (2010-2025),
--     IRENA Renewable Capacity Statistics 2025 (annual change tables),
--     national regulators: BNetzA Marktstammdatenregister (DE), REE/CNMC
--     statistical reports (ES), RTE Panorama de l'électricité renouvelable
--     (FR), Energistyrelsen Stamdataregister (DK), CBS / RVO (NL),
--     Terna anagrafica impianti (IT), Energimyndigheten (SE), URE Annual
--     Report (PL), ANEEL BIG (BR), AEMO/Clean Energy Council (AU),
--     CRE/CENACE/SENER (MX), TEİAŞ/EPDK (TR).
--   • Wind offshore: WindEurope offshore statistics (2009-2025), 4COffshore
--     and BNEF Offshore Wind Market Outlooks, BSH/BNetzA (DE),
--     Energistyrelsen offshore registry (DK), FPS Economy / Elia (BE),
--     RVO (NL), US BOEM Renewable Energy Programs Office, Taiwan MoEA
--     Bureau of Energy.
--   • Solar PV: IEA-PVPS "Snapshot of Global PV Markets" 2011-2025,
--     SolarPower Europe "Global Market Outlook" 2014-2025, Eurostat
--     nrg_inf_epc, BMWi/BNetzA (DE), REE / IDAE / UNEF (ES), Terna /
--     GSE (IT), RTE / SDES (FR), BEIS DUKES / Solar Energy UK (GB),
--     CBS / RVO (NL), APERe (BE), AEMO / Clean Energy Regulator (AU),
--     METI / ANRE FIT register (JP), EIA Form 860 (US).
--   • BESS: BNEF Energy Storage Market Outlook (1H/2H 2022-2025),
--     IEA Energy Storage Tracker, Wood Mackenzie Energy Storage Service,
--     EASE-Frith European Market Monitor on Energy Storage 2024,
--     Modo Energy GB BESS index, EIA Form 860 large-scale battery
--     register, Clean Energy Council BESS report (AU), Terna (IT),
--     KEPCO / KESIA (KR), METI ANRE (JP), Eirgrid DS3 register (IE).
--
-- Cross-validated against IRENA Renewable Capacity Statistics 2025
-- cumulative totals (within 10% per country, except where flagged in
-- the migration trailer notes).
--
-- China is intentionally excluded for offshore (and not in Tier 1 scope
-- for any class) per product decision: distortion + non-addressable
-- market for the asset-owner audience.

-- ════════════════════════════════════════════════════════════════════════
-- WIND ONSHORE — annual MW added (2000-2025)
-- ════════════════════════════════════════════════════════════════════════

INSERT INTO installation_history
  (asset_class, country, region, year, capacity_mw, duration_h, source_publisher, source_url) VALUES

  -- Germany (BNetzA Marktstammdatenregister + WindEurope)
  ('wind_onshore','DE','Germany',2000, 1665, NULL, 'WindEurope / BNetzA', 'https://windeurope.org/intelligence-platform/product/wind-energy-in-europe-2024-statistics-and-the-outlook-for-2025-2030/'),
  ('wind_onshore','DE','Germany',2001, 2659, NULL, 'WindEurope / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('wind_onshore','DE','Germany',2002, 3247, NULL, 'WindEurope / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('wind_onshore','DE','Germany',2003, 2645, NULL, 'WindEurope / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('wind_onshore','DE','Germany',2004, 2037, NULL, 'WindEurope / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('wind_onshore','DE','Germany',2005, 1808, NULL, 'WindEurope / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('wind_onshore','DE','Germany',2006, 2233, NULL, 'WindEurope / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('wind_onshore','DE','Germany',2007, 1667, NULL, 'WindEurope / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('wind_onshore','DE','Germany',2008, 1665, NULL, 'WindEurope / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('wind_onshore','DE','Germany',2009, 1917, NULL, 'WindEurope / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('wind_onshore','DE','Germany',2010, 1551, NULL, 'WindEurope / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('wind_onshore','DE','Germany',2011, 2007, NULL, 'WindEurope / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('wind_onshore','DE','Germany',2012, 2415, NULL, 'WindEurope / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('wind_onshore','DE','Germany',2013, 2998, NULL, 'WindEurope / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('wind_onshore','DE','Germany',2014, 4750, NULL, 'WindEurope / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('wind_onshore','DE','Germany',2015, 3536, NULL, 'WindEurope / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('wind_onshore','DE','Germany',2016, 4625, NULL, 'WindEurope / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('wind_onshore','DE','Germany',2017, 5334, NULL, 'WindEurope / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('wind_onshore','DE','Germany',2018, 2402, NULL, 'WindEurope / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('wind_onshore','DE','Germany',2019, 1078, NULL, 'WindEurope / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('wind_onshore','DE','Germany',2020, 1431, NULL, 'WindEurope / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('wind_onshore','DE','Germany',2021, 1925, NULL, 'WindEurope / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('wind_onshore','DE','Germany',2022, 2403, NULL, 'WindEurope / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('wind_onshore','DE','Germany',2023, 3567, NULL, 'WindEurope / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('wind_onshore','DE','Germany',2024, 4042, NULL, 'WindEurope / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('wind_onshore','DE','Germany',2025, 4500, NULL, 'WindEurope / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),

  -- Spain (REE / AEE / WindEurope)
  ('wind_onshore','ES','Spain',2000,  710, NULL, 'WindEurope / REE', 'https://www.ree.es/en/datos/generation'),
  ('wind_onshore','ES','Spain',2001, 1050, NULL, 'WindEurope / REE', 'https://www.ree.es/en/datos/generation'),
  ('wind_onshore','ES','Spain',2002, 1493, NULL, 'WindEurope / REE', 'https://www.ree.es/en/datos/generation'),
  ('wind_onshore','ES','Spain',2003, 1377, NULL, 'WindEurope / REE', 'https://www.ree.es/en/datos/generation'),
  ('wind_onshore','ES','Spain',2004, 2065, NULL, 'WindEurope / REE', 'https://www.ree.es/en/datos/generation'),
  ('wind_onshore','ES','Spain',2005, 1764, NULL, 'WindEurope / REE', 'https://www.ree.es/en/datos/generation'),
  ('wind_onshore','ES','Spain',2006, 1587, NULL, 'WindEurope / REE', 'https://www.ree.es/en/datos/generation'),
  ('wind_onshore','ES','Spain',2007, 3522, NULL, 'WindEurope / REE', 'https://www.ree.es/en/datos/generation'),
  ('wind_onshore','ES','Spain',2008, 1739, NULL, 'WindEurope / REE', 'https://www.ree.es/en/datos/generation'),
  ('wind_onshore','ES','Spain',2009, 2459, NULL, 'WindEurope / REE', 'https://www.ree.es/en/datos/generation'),
  ('wind_onshore','ES','Spain',2010, 1516, NULL, 'WindEurope / REE', 'https://www.ree.es/en/datos/generation'),
  ('wind_onshore','ES','Spain',2011, 1050, NULL, 'WindEurope / REE', 'https://www.ree.es/en/datos/generation'),
  ('wind_onshore','ES','Spain',2012, 1122, NULL, 'WindEurope / REE', 'https://www.ree.es/en/datos/generation'),
  ('wind_onshore','ES','Spain',2013,  175, NULL, 'WindEurope / REE', 'https://www.ree.es/en/datos/generation'),
  ('wind_onshore','ES','Spain',2014,   28, NULL, 'WindEurope / REE', 'https://www.ree.es/en/datos/generation'),
  ('wind_onshore','ES','Spain',2015,    0, NULL, 'WindEurope / REE', 'https://www.ree.es/en/datos/generation'),
  ('wind_onshore','ES','Spain',2016,   38, NULL, 'WindEurope / REE', 'https://www.ree.es/en/datos/generation'),
  ('wind_onshore','ES','Spain',2017,   96, NULL, 'WindEurope / REE', 'https://www.ree.es/en/datos/generation'),
  ('wind_onshore','ES','Spain',2018,  393, NULL, 'WindEurope / REE', 'https://www.ree.es/en/datos/generation'),
  ('wind_onshore','ES','Spain',2019, 2319, NULL, 'WindEurope / REE', 'https://www.ree.es/en/datos/generation'),
  ('wind_onshore','ES','Spain',2020, 1720, NULL, 'WindEurope / REE', 'https://www.ree.es/en/datos/generation'),
  ('wind_onshore','ES','Spain',2021,  842, NULL, 'WindEurope / REE', 'https://www.ree.es/en/datos/generation'),
  ('wind_onshore','ES','Spain',2022, 1670, NULL, 'WindEurope / REE', 'https://www.ree.es/en/datos/generation'),
  ('wind_onshore','ES','Spain',2023, 1300, NULL, 'WindEurope / REE', 'https://www.ree.es/en/datos/generation'),
  ('wind_onshore','ES','Spain',2024, 1100, NULL, 'WindEurope / REE', 'https://www.ree.es/en/datos/generation'),
  ('wind_onshore','ES','Spain',2025, 1400, NULL, 'WindEurope / REE', 'https://www.ree.es/en/datos/generation'),

  -- France (RTE Panorama / SDES)
  ('wind_onshore','FR','France',2000,   38, NULL, 'WindEurope / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('wind_onshore','FR','France',2001,   29, NULL, 'WindEurope / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('wind_onshore','FR','France',2002,   59, NULL, 'WindEurope / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('wind_onshore','FR','France',2003,   91, NULL, 'WindEurope / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('wind_onshore','FR','France',2004,  138, NULL, 'WindEurope / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('wind_onshore','FR','France',2005,  389, NULL, 'WindEurope / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('wind_onshore','FR','France',2006,  810, NULL, 'WindEurope / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('wind_onshore','FR','France',2007,  888, NULL, 'WindEurope / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('wind_onshore','FR','France',2008,  950, NULL, 'WindEurope / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('wind_onshore','FR','France',2009, 1088, NULL, 'WindEurope / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('wind_onshore','FR','France',2010, 1086, NULL, 'WindEurope / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('wind_onshore','FR','France',2011,  830, NULL, 'WindEurope / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('wind_onshore','FR','France',2012,  757, NULL, 'WindEurope / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('wind_onshore','FR','France',2013,  631, NULL, 'WindEurope / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('wind_onshore','FR','France',2014, 1042, NULL, 'WindEurope / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('wind_onshore','FR','France',2015, 1067, NULL, 'WindEurope / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('wind_onshore','FR','France',2016, 1561, NULL, 'WindEurope / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('wind_onshore','FR','France',2017, 1797, NULL, 'WindEurope / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('wind_onshore','FR','France',2018, 1565, NULL, 'WindEurope / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('wind_onshore','FR','France',2019, 1361, NULL, 'WindEurope / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('wind_onshore','FR','France',2020, 1108, NULL, 'WindEurope / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('wind_onshore','FR','France',2021, 1209, NULL, 'WindEurope / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('wind_onshore','FR','France',2022, 1929, NULL, 'WindEurope / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('wind_onshore','FR','France',2023, 1435, NULL, 'WindEurope / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('wind_onshore','FR','France',2024, 1570, NULL, 'WindEurope / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('wind_onshore','FR','France',2025, 1700, NULL, 'WindEurope / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),

  -- Denmark (Energistyrelsen Stamdataregister)
  ('wind_onshore','DK','Denmark',2000, 113, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_onshore','DK','Denmark',2001, 116, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_onshore','DK','Denmark',2002, 481, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_onshore','DK','Denmark',2003,  10, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_onshore','DK','Denmark',2004,   7, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_onshore','DK','Denmark',2005,  17, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_onshore','DK','Denmark',2006,   9, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_onshore','DK','Denmark',2007,   3, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_onshore','DK','Denmark',2008,  77, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_onshore','DK','Denmark',2009, 254, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_onshore','DK','Denmark',2010, 220, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_onshore','DK','Denmark',2011, 178, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_onshore','DK','Denmark',2012, 217, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_onshore','DK','Denmark',2013, 657, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_onshore','DK','Denmark',2014,  68, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_onshore','DK','Denmark',2015, 217, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_onshore','DK','Denmark',2016, 220, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_onshore','DK','Denmark',2017, 333, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_onshore','DK','Denmark',2018, 173, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_onshore','DK','Denmark',2019, 116, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_onshore','DK','Denmark',2020,  37, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_onshore','DK','Denmark',2021,  68, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_onshore','DK','Denmark',2022, 174, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_onshore','DK','Denmark',2023, 200, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_onshore','DK','Denmark',2024, 240, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_onshore','DK','Denmark',2025, 260, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),

  -- Netherlands (CBS / RVO)
  ('wind_onshore','NL','Netherlands',2000,  53, NULL, 'WindEurope / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('wind_onshore','NL','Netherlands',2001,  46, NULL, 'WindEurope / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('wind_onshore','NL','Netherlands',2002, 217, NULL, 'WindEurope / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('wind_onshore','NL','Netherlands',2003, 235, NULL, 'WindEurope / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('wind_onshore','NL','Netherlands',2004, 200, NULL, 'WindEurope / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('wind_onshore','NL','Netherlands',2005, 213, NULL, 'WindEurope / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('wind_onshore','NL','Netherlands',2006, 357, NULL, 'WindEurope / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('wind_onshore','NL','Netherlands',2007, 197, NULL, 'WindEurope / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('wind_onshore','NL','Netherlands',2008, 504, NULL, 'WindEurope / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('wind_onshore','NL','Netherlands',2009,  39, NULL, 'WindEurope / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('wind_onshore','NL','Netherlands',2010,  38, NULL, 'WindEurope / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('wind_onshore','NL','Netherlands',2011,  78, NULL, 'WindEurope / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('wind_onshore','NL','Netherlands',2012, 106, NULL, 'WindEurope / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('wind_onshore','NL','Netherlands',2013, 303, NULL, 'WindEurope / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('wind_onshore','NL','Netherlands',2014, 141, NULL, 'WindEurope / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('wind_onshore','NL','Netherlands',2015, 567, NULL, 'WindEurope / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('wind_onshore','NL','Netherlands',2016, 691, NULL, 'WindEurope / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('wind_onshore','NL','Netherlands',2017, 188, NULL, 'WindEurope / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('wind_onshore','NL','Netherlands',2018, 260, NULL, 'WindEurope / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('wind_onshore','NL','Netherlands',2019, 568, NULL, 'WindEurope / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('wind_onshore','NL','Netherlands',2020, 743, NULL, 'WindEurope / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('wind_onshore','NL','Netherlands',2021, 759, NULL, 'WindEurope / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('wind_onshore','NL','Netherlands',2022, 458, NULL, 'WindEurope / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('wind_onshore','NL','Netherlands',2023, 350, NULL, 'WindEurope / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('wind_onshore','NL','Netherlands',2024, 410, NULL, 'WindEurope / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('wind_onshore','NL','Netherlands',2025, 480, NULL, 'WindEurope / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),

  -- Italy (Terna / GSE)
  ('wind_onshore','IT','Italy',2000,  90, NULL, 'WindEurope / Terna', 'https://www.terna.it/en/electric-system/statistical-data-forecast'),
  ('wind_onshore','IT','Italy',2001, 222, NULL, 'WindEurope / Terna', 'https://www.terna.it/en/electric-system/statistical-data-forecast'),
  ('wind_onshore','IT','Italy',2002, 100, NULL, 'WindEurope / Terna', 'https://www.terna.it/en/electric-system/statistical-data-forecast'),
  ('wind_onshore','IT','Italy',2003, 116, NULL, 'WindEurope / Terna', 'https://www.terna.it/en/electric-system/statistical-data-forecast'),
  ('wind_onshore','IT','Italy',2004, 357, NULL, 'WindEurope / Terna', 'https://www.terna.it/en/electric-system/statistical-data-forecast'),
  ('wind_onshore','IT','Italy',2005, 452, NULL, 'WindEurope / Terna', 'https://www.terna.it/en/electric-system/statistical-data-forecast'),
  ('wind_onshore','IT','Italy',2006, 405, NULL, 'WindEurope / Terna', 'https://www.terna.it/en/electric-system/statistical-data-forecast'),
  ('wind_onshore','IT','Italy',2007, 603, NULL, 'WindEurope / Terna', 'https://www.terna.it/en/electric-system/statistical-data-forecast'),
  ('wind_onshore','IT','Italy',2008, 1010, NULL, 'WindEurope / Terna', 'https://www.terna.it/en/electric-system/statistical-data-forecast'),
  ('wind_onshore','IT','Italy',2009, 1113, NULL, 'WindEurope / Terna', 'https://www.terna.it/en/electric-system/statistical-data-forecast'),
  ('wind_onshore','IT','Italy',2010, 950, NULL, 'WindEurope / Terna', 'https://www.terna.it/en/electric-system/statistical-data-forecast'),
  ('wind_onshore','IT','Italy',2011, 951, NULL, 'WindEurope / Terna', 'https://www.terna.it/en/electric-system/statistical-data-forecast'),
  ('wind_onshore','IT','Italy',2012, 1273, NULL, 'WindEurope / Terna', 'https://www.terna.it/en/electric-system/statistical-data-forecast'),
  ('wind_onshore','IT','Italy',2013, 444, NULL, 'WindEurope / Terna', 'https://www.terna.it/en/electric-system/statistical-data-forecast'),
  ('wind_onshore','IT','Italy',2014, 108, NULL, 'WindEurope / Terna', 'https://www.terna.it/en/electric-system/statistical-data-forecast'),
  ('wind_onshore','IT','Italy',2015, 295, NULL, 'WindEurope / Terna', 'https://www.terna.it/en/electric-system/statistical-data-forecast'),
  ('wind_onshore','IT','Italy',2016, 282, NULL, 'WindEurope / Terna', 'https://www.terna.it/en/electric-system/statistical-data-forecast'),
  ('wind_onshore','IT','Italy',2017, 252, NULL, 'WindEurope / Terna', 'https://www.terna.it/en/electric-system/statistical-data-forecast'),
  ('wind_onshore','IT','Italy',2018, 432, NULL, 'WindEurope / Terna', 'https://www.terna.it/en/electric-system/statistical-data-forecast'),
  ('wind_onshore','IT','Italy',2019, 374, NULL, 'WindEurope / Terna', 'https://www.terna.it/en/electric-system/statistical-data-forecast'),
  ('wind_onshore','IT','Italy',2020, 100, NULL, 'WindEurope / Terna', 'https://www.terna.it/en/electric-system/statistical-data-forecast'),
  ('wind_onshore','IT','Italy',2021, 134, NULL, 'WindEurope / Terna', 'https://www.terna.it/en/electric-system/statistical-data-forecast'),
  ('wind_onshore','IT','Italy',2022, 525, NULL, 'WindEurope / Terna', 'https://www.terna.it/en/electric-system/statistical-data-forecast'),
  ('wind_onshore','IT','Italy',2023, 487, NULL, 'WindEurope / Terna', 'https://www.terna.it/en/electric-system/statistical-data-forecast'),
  ('wind_onshore','IT','Italy',2024, 760, NULL, 'WindEurope / Terna', 'https://www.terna.it/en/electric-system/statistical-data-forecast'),
  ('wind_onshore','IT','Italy',2025, 900, NULL, 'WindEurope / Terna', 'https://www.terna.it/en/electric-system/statistical-data-forecast'),

  -- Sweden (Energimyndigheten / Svensk Vindenergi)
  ('wind_onshore','SE','Sweden',2000,  10, NULL, 'WindEurope / Energimyndigheten', 'https://www.energimyndigheten.se/statistik/'),
  ('wind_onshore','SE','Sweden',2001,  35, NULL, 'WindEurope / Energimyndigheten', 'https://www.energimyndigheten.se/statistik/'),
  ('wind_onshore','SE','Sweden',2002,  45, NULL, 'WindEurope / Energimyndigheten', 'https://www.energimyndigheten.se/statistik/'),
  ('wind_onshore','SE','Sweden',2003,  56, NULL, 'WindEurope / Energimyndigheten', 'https://www.energimyndigheten.se/statistik/'),
  ('wind_onshore','SE','Sweden',2004,  47, NULL, 'WindEurope / Energimyndigheten', 'https://www.energimyndigheten.se/statistik/'),
  ('wind_onshore','SE','Sweden',2005,  77, NULL, 'WindEurope / Energimyndigheten', 'https://www.energimyndigheten.se/statistik/'),
  ('wind_onshore','SE','Sweden',2006,  62, NULL, 'WindEurope / Energimyndigheten', 'https://www.energimyndigheten.se/statistik/'),
  ('wind_onshore','SE','Sweden',2007, 217, NULL, 'WindEurope / Energimyndigheten', 'https://www.energimyndigheten.se/statistik/'),
  ('wind_onshore','SE','Sweden',2008, 236, NULL, 'WindEurope / Energimyndigheten', 'https://www.energimyndigheten.se/statistik/'),
  ('wind_onshore','SE','Sweden',2009, 365, NULL, 'WindEurope / Energimyndigheten', 'https://www.energimyndigheten.se/statistik/'),
  ('wind_onshore','SE','Sweden',2010, 615, NULL, 'WindEurope / Energimyndigheten', 'https://www.energimyndigheten.se/statistik/'),
  ('wind_onshore','SE','Sweden',2011, 763, NULL, 'WindEurope / Energimyndigheten', 'https://www.energimyndigheten.se/statistik/'),
  ('wind_onshore','SE','Sweden',2012, 894, NULL, 'WindEurope / Energimyndigheten', 'https://www.energimyndigheten.se/statistik/'),
  ('wind_onshore','SE','Sweden',2013, 689, NULL, 'WindEurope / Energimyndigheten', 'https://www.energimyndigheten.se/statistik/'),
  ('wind_onshore','SE','Sweden',2014, 1052, NULL, 'WindEurope / Energimyndigheten', 'https://www.energimyndigheten.se/statistik/'),
  ('wind_onshore','SE','Sweden',2015, 615, NULL, 'WindEurope / Energimyndigheten', 'https://www.energimyndigheten.se/statistik/'),
  ('wind_onshore','SE','Sweden',2016, 493, NULL, 'WindEurope / Energimyndigheten', 'https://www.energimyndigheten.se/statistik/'),
  ('wind_onshore','SE','Sweden',2017, 197, NULL, 'WindEurope / Energimyndigheten', 'https://www.energimyndigheten.se/statistik/'),
  ('wind_onshore','SE','Sweden',2018, 717, NULL, 'WindEurope / Energimyndigheten', 'https://www.energimyndigheten.se/statistik/'),
  ('wind_onshore','SE','Sweden',2019, 1607, NULL, 'WindEurope / Energimyndigheten', 'https://www.energimyndigheten.se/statistik/'),
  ('wind_onshore','SE','Sweden',2020, 1397, NULL, 'WindEurope / Energimyndigheten', 'https://www.energimyndigheten.se/statistik/'),
  ('wind_onshore','SE','Sweden',2021, 2105, NULL, 'WindEurope / Energimyndigheten', 'https://www.energimyndigheten.se/statistik/'),
  ('wind_onshore','SE','Sweden',2022, 2436, NULL, 'WindEurope / Energimyndigheten', 'https://www.energimyndigheten.se/statistik/'),
  ('wind_onshore','SE','Sweden',2023, 1900, NULL, 'WindEurope / Energimyndigheten', 'https://www.energimyndigheten.se/statistik/'),
  ('wind_onshore','SE','Sweden',2024, 1100, NULL, 'WindEurope / Energimyndigheten', 'https://www.energimyndigheten.se/statistik/'),
  ('wind_onshore','SE','Sweden',2025, 900, NULL, 'WindEurope / Energimyndigheten', 'https://www.energimyndigheten.se/statistik/'),

  -- Poland (URE / PSE)
  ('wind_onshore','PL','Poland',2000,   2, NULL, 'WindEurope / URE', 'https://www.ure.gov.pl/en/markets/electricity'),
  ('wind_onshore','PL','Poland',2001,   3, NULL, 'WindEurope / URE', 'https://www.ure.gov.pl/en/markets/electricity'),
  ('wind_onshore','PL','Poland',2002,   2, NULL, 'WindEurope / URE', 'https://www.ure.gov.pl/en/markets/electricity'),
  ('wind_onshore','PL','Poland',2003,   5, NULL, 'WindEurope / URE', 'https://www.ure.gov.pl/en/markets/electricity'),
  ('wind_onshore','PL','Poland',2004,  31, NULL, 'WindEurope / URE', 'https://www.ure.gov.pl/en/markets/electricity'),
  ('wind_onshore','PL','Poland',2005,  17, NULL, 'WindEurope / URE', 'https://www.ure.gov.pl/en/markets/electricity'),
  ('wind_onshore','PL','Poland',2006,  19, NULL, 'WindEurope / URE', 'https://www.ure.gov.pl/en/markets/electricity'),
  ('wind_onshore','PL','Poland',2007,  121, NULL, 'WindEurope / URE', 'https://www.ure.gov.pl/en/markets/electricity'),
  ('wind_onshore','PL','Poland',2008,  192, NULL, 'WindEurope / URE', 'https://www.ure.gov.pl/en/markets/electricity'),
  ('wind_onshore','PL','Poland',2009,  269, NULL, 'WindEurope / URE', 'https://www.ure.gov.pl/en/markets/electricity'),
  ('wind_onshore','PL','Poland',2010,  386, NULL, 'WindEurope / URE', 'https://www.ure.gov.pl/en/markets/electricity'),
  ('wind_onshore','PL','Poland',2011,  428, NULL, 'WindEurope / URE', 'https://www.ure.gov.pl/en/markets/electricity'),
  ('wind_onshore','PL','Poland',2012,  880, NULL, 'WindEurope / URE', 'https://www.ure.gov.pl/en/markets/electricity'),
  ('wind_onshore','PL','Poland',2013,  894, NULL, 'WindEurope / URE', 'https://www.ure.gov.pl/en/markets/electricity'),
  ('wind_onshore','PL','Poland',2014,  444, NULL, 'WindEurope / URE', 'https://www.ure.gov.pl/en/markets/electricity'),
  ('wind_onshore','PL','Poland',2015, 1266, NULL, 'WindEurope / URE', 'https://www.ure.gov.pl/en/markets/electricity'),
  ('wind_onshore','PL','Poland',2016,  682, NULL, 'WindEurope / URE', 'https://www.ure.gov.pl/en/markets/electricity'),
  ('wind_onshore','PL','Poland',2017,   41, NULL, 'WindEurope / URE', 'https://www.ure.gov.pl/en/markets/electricity'),
  ('wind_onshore','PL','Poland',2018,    9, NULL, 'WindEurope / URE', 'https://www.ure.gov.pl/en/markets/electricity'),
  ('wind_onshore','PL','Poland',2019,   45, NULL, 'WindEurope / URE', 'https://www.ure.gov.pl/en/markets/electricity'),
  ('wind_onshore','PL','Poland',2020,  357, NULL, 'WindEurope / URE', 'https://www.ure.gov.pl/en/markets/electricity'),
  ('wind_onshore','PL','Poland',2021,  475, NULL, 'WindEurope / URE', 'https://www.ure.gov.pl/en/markets/electricity'),
  ('wind_onshore','PL','Poland',2022,  674, NULL, 'WindEurope / URE', 'https://www.ure.gov.pl/en/markets/electricity'),
  ('wind_onshore','PL','Poland',2023,  830, NULL, 'WindEurope / URE', 'https://www.ure.gov.pl/en/markets/electricity'),
  ('wind_onshore','PL','Poland',2024, 1100, NULL, 'WindEurope / URE', 'https://www.ure.gov.pl/en/markets/electricity'),
  ('wind_onshore','PL','Poland',2025, 1300, NULL, 'WindEurope / URE', 'https://www.ure.gov.pl/en/markets/electricity'),

  -- Brazil (ANEEL BIG / ABEEolica / GWEC)
  ('wind_onshore','BR','Brazil',2005,  29, NULL, 'GWEC / ANEEL', 'https://www.gov.br/aneel/pt-br/centrais-de-conteudos/relatorios-e-indicadores'),
  ('wind_onshore','BR','Brazil',2006,  208, NULL, 'GWEC / ANEEL', 'https://www.gov.br/aneel/pt-br/centrais-de-conteudos/relatorios-e-indicadores'),
  ('wind_onshore','BR','Brazil',2007,   10, NULL, 'GWEC / ANEEL', 'https://www.gov.br/aneel/pt-br/centrais-de-conteudos/relatorios-e-indicadores'),
  ('wind_onshore','BR','Brazil',2008,   94, NULL, 'GWEC / ANEEL', 'https://www.gov.br/aneel/pt-br/centrais-de-conteudos/relatorios-e-indicadores'),
  ('wind_onshore','BR','Brazil',2009,  264, NULL, 'GWEC / ANEEL', 'https://www.gov.br/aneel/pt-br/centrais-de-conteudos/relatorios-e-indicadores'),
  ('wind_onshore','BR','Brazil',2010,  326, NULL, 'GWEC / ANEEL', 'https://www.gov.br/aneel/pt-br/centrais-de-conteudos/relatorios-e-indicadores'),
  ('wind_onshore','BR','Brazil',2011,  583, NULL, 'GWEC / ANEEL', 'https://www.gov.br/aneel/pt-br/centrais-de-conteudos/relatorios-e-indicadores'),
  ('wind_onshore','BR','Brazil',2012, 1077, NULL, 'GWEC / ANEEL', 'https://www.gov.br/aneel/pt-br/centrais-de-conteudos/relatorios-e-indicadores'),
  ('wind_onshore','BR','Brazil',2013,  948, NULL, 'GWEC / ANEEL', 'https://www.gov.br/aneel/pt-br/centrais-de-conteudos/relatorios-e-indicadores'),
  ('wind_onshore','BR','Brazil',2014, 2783, NULL, 'GWEC / ANEEL', 'https://www.gov.br/aneel/pt-br/centrais-de-conteudos/relatorios-e-indicadores'),
  ('wind_onshore','BR','Brazil',2015, 2754, NULL, 'GWEC / ANEEL', 'https://www.gov.br/aneel/pt-br/centrais-de-conteudos/relatorios-e-indicadores'),
  ('wind_onshore','BR','Brazil',2016, 2014, NULL, 'GWEC / ANEEL', 'https://www.gov.br/aneel/pt-br/centrais-de-conteudos/relatorios-e-indicadores'),
  ('wind_onshore','BR','Brazil',2017, 2027, NULL, 'GWEC / ANEEL', 'https://www.gov.br/aneel/pt-br/centrais-de-conteudos/relatorios-e-indicadores'),
  ('wind_onshore','BR','Brazil',2018,  840, NULL, 'GWEC / ANEEL', 'https://www.gov.br/aneel/pt-br/centrais-de-conteudos/relatorios-e-indicadores'),
  ('wind_onshore','BR','Brazil',2019,  745, NULL, 'GWEC / ANEEL', 'https://www.gov.br/aneel/pt-br/centrais-de-conteudos/relatorios-e-indicadores'),
  ('wind_onshore','BR','Brazil',2020, 2316, NULL, 'GWEC / ANEEL', 'https://www.gov.br/aneel/pt-br/centrais-de-conteudos/relatorios-e-indicadores'),
  ('wind_onshore','BR','Brazil',2021, 3829, NULL, 'GWEC / ANEEL', 'https://www.gov.br/aneel/pt-br/centrais-de-conteudos/relatorios-e-indicadores'),
  ('wind_onshore','BR','Brazil',2022, 4082, NULL, 'GWEC / ANEEL', 'https://www.gov.br/aneel/pt-br/centrais-de-conteudos/relatorios-e-indicadores'),
  ('wind_onshore','BR','Brazil',2023, 4838, NULL, 'GWEC / ANEEL', 'https://www.gov.br/aneel/pt-br/centrais-de-conteudos/relatorios-e-indicadores'),
  ('wind_onshore','BR','Brazil',2024, 3300, NULL, 'GWEC / ANEEL', 'https://www.gov.br/aneel/pt-br/centrais-de-conteudos/relatorios-e-indicadores'),
  ('wind_onshore','BR','Brazil',2025, 3500, NULL, 'GWEC / ANEEL', 'https://www.gov.br/aneel/pt-br/centrais-de-conteudos/relatorios-e-indicadores'),

  -- Australia (Clean Energy Council / AEMO)
  ('wind_onshore','AU','Australia',2003,  72, NULL, 'GWEC / Clean Energy Council', 'https://www.cleanenergycouncil.org.au/resources/resources-hub/clean-energy-australia-report'),
  ('wind_onshore','AU','Australia',2004,  56, NULL, 'GWEC / Clean Energy Council', 'https://www.cleanenergycouncil.org.au/resources/resources-hub/clean-energy-australia-report'),
  ('wind_onshore','AU','Australia',2005, 169, NULL, 'GWEC / Clean Energy Council', 'https://www.cleanenergycouncil.org.au/resources/resources-hub/clean-energy-australia-report'),
  ('wind_onshore','AU','Australia',2006,  92, NULL, 'GWEC / Clean Energy Council', 'https://www.cleanenergycouncil.org.au/resources/resources-hub/clean-energy-australia-report'),
  ('wind_onshore','AU','Australia',2007,   4, NULL, 'GWEC / Clean Energy Council', 'https://www.cleanenergycouncil.org.au/resources/resources-hub/clean-energy-australia-report'),
  ('wind_onshore','AU','Australia',2008, 482, NULL, 'GWEC / Clean Energy Council', 'https://www.cleanenergycouncil.org.au/resources/resources-hub/clean-energy-australia-report'),
  ('wind_onshore','AU','Australia',2009, 484, NULL, 'GWEC / Clean Energy Council', 'https://www.cleanenergycouncil.org.au/resources/resources-hub/clean-energy-australia-report'),
  ('wind_onshore','AU','Australia',2010, 167, NULL, 'GWEC / Clean Energy Council', 'https://www.cleanenergycouncil.org.au/resources/resources-hub/clean-energy-australia-report'),
  ('wind_onshore','AU','Australia',2011, 233, NULL, 'GWEC / Clean Energy Council', 'https://www.cleanenergycouncil.org.au/resources/resources-hub/clean-energy-australia-report'),
  ('wind_onshore','AU','Australia',2012, 358, NULL, 'GWEC / Clean Energy Council', 'https://www.cleanenergycouncil.org.au/resources/resources-hub/clean-energy-australia-report'),
  ('wind_onshore','AU','Australia',2013, 651, NULL, 'GWEC / Clean Energy Council', 'https://www.cleanenergycouncil.org.au/resources/resources-hub/clean-energy-australia-report'),
  ('wind_onshore','AU','Australia',2014, 567, NULL, 'GWEC / Clean Energy Council', 'https://www.cleanenergycouncil.org.au/resources/resources-hub/clean-energy-australia-report'),
  ('wind_onshore','AU','Australia',2015,   0, NULL, 'GWEC / Clean Energy Council', 'https://www.cleanenergycouncil.org.au/resources/resources-hub/clean-energy-australia-report'),
  ('wind_onshore','AU','Australia',2016, 140, NULL, 'GWEC / Clean Energy Council', 'https://www.cleanenergycouncil.org.au/resources/resources-hub/clean-energy-australia-report'),
  ('wind_onshore','AU','Australia',2017, 245, NULL, 'GWEC / Clean Energy Council', 'https://www.cleanenergycouncil.org.au/resources/resources-hub/clean-energy-australia-report'),
  ('wind_onshore','AU','Australia',2018, 549, NULL, 'GWEC / Clean Energy Council', 'https://www.cleanenergycouncil.org.au/resources/resources-hub/clean-energy-australia-report'),
  ('wind_onshore','AU','Australia',2019, 837, NULL, 'GWEC / Clean Energy Council', 'https://www.cleanenergycouncil.org.au/resources/resources-hub/clean-energy-australia-report'),
  ('wind_onshore','AU','Australia',2020, 1097, NULL, 'GWEC / Clean Energy Council', 'https://www.cleanenergycouncil.org.au/resources/resources-hub/clean-energy-australia-report'),
  ('wind_onshore','AU','Australia',2021, 354, NULL, 'GWEC / Clean Energy Council', 'https://www.cleanenergycouncil.org.au/resources/resources-hub/clean-energy-australia-report'),
  ('wind_onshore','AU','Australia',2022, 705, NULL, 'GWEC / Clean Energy Council', 'https://www.cleanenergycouncil.org.au/resources/resources-hub/clean-energy-australia-report'),
  ('wind_onshore','AU','Australia',2023, 1416, NULL, 'GWEC / Clean Energy Council', 'https://www.cleanenergycouncil.org.au/resources/resources-hub/clean-energy-australia-report'),
  ('wind_onshore','AU','Australia',2024, 1100, NULL, 'GWEC / Clean Energy Council', 'https://www.cleanenergycouncil.org.au/resources/resources-hub/clean-energy-australia-report'),
  ('wind_onshore','AU','Australia',2025, 1300, NULL, 'GWEC / Clean Energy Council', 'https://www.cleanenergycouncil.org.au/resources/resources-hub/clean-energy-australia-report'),

  -- Mexico (CRE / CENACE / GWEC)
  ('wind_onshore','MX','Mexico',2007,    0, NULL, 'GWEC / CRE', 'https://www.cenace.gob.mx/Paginas/SIM/Reportes/EnergiaGenerada.aspx'),
  ('wind_onshore','MX','Mexico',2008,   85, NULL, 'GWEC / CRE', 'https://www.cenace.gob.mx/Paginas/SIM/Reportes/EnergiaGenerada.aspx'),
  ('wind_onshore','MX','Mexico',2009,  117, NULL, 'GWEC / CRE', 'https://www.cenace.gob.mx/Paginas/SIM/Reportes/EnergiaGenerada.aspx'),
  ('wind_onshore','MX','Mexico',2010,  316, NULL, 'GWEC / CRE', 'https://www.cenace.gob.mx/Paginas/SIM/Reportes/EnergiaGenerada.aspx'),
  ('wind_onshore','MX','Mexico',2011,  52, NULL, 'GWEC / CRE', 'https://www.cenace.gob.mx/Paginas/SIM/Reportes/EnergiaGenerada.aspx'),
  ('wind_onshore','MX','Mexico',2012, 801, NULL, 'GWEC / CRE', 'https://www.cenace.gob.mx/Paginas/SIM/Reportes/EnergiaGenerada.aspx'),
  ('wind_onshore','MX','Mexico',2013,  377, NULL, 'GWEC / CRE', 'https://www.cenace.gob.mx/Paginas/SIM/Reportes/EnergiaGenerada.aspx'),
  ('wind_onshore','MX','Mexico',2014,  522, NULL, 'GWEC / CRE', 'https://www.cenace.gob.mx/Paginas/SIM/Reportes/EnergiaGenerada.aspx'),
  ('wind_onshore','MX','Mexico',2015, 714, NULL, 'GWEC / CRE', 'https://www.cenace.gob.mx/Paginas/SIM/Reportes/EnergiaGenerada.aspx'),
  ('wind_onshore','MX','Mexico',2016, 454, NULL, 'GWEC / CRE', 'https://www.cenace.gob.mx/Paginas/SIM/Reportes/EnergiaGenerada.aspx'),
  ('wind_onshore','MX','Mexico',2017, 396, NULL, 'GWEC / CRE', 'https://www.cenace.gob.mx/Paginas/SIM/Reportes/EnergiaGenerada.aspx'),
  ('wind_onshore','MX','Mexico',2018, 928, NULL, 'GWEC / CRE', 'https://www.cenace.gob.mx/Paginas/SIM/Reportes/EnergiaGenerada.aspx'),
  ('wind_onshore','MX','Mexico',2019, 1281, NULL, 'GWEC / CRE', 'https://www.cenace.gob.mx/Paginas/SIM/Reportes/EnergiaGenerada.aspx'),
  ('wind_onshore','MX','Mexico',2020, 588, NULL, 'GWEC / CRE', 'https://www.cenace.gob.mx/Paginas/SIM/Reportes/EnergiaGenerada.aspx'),
  ('wind_onshore','MX','Mexico',2021, 256, NULL, 'GWEC / CRE', 'https://www.cenace.gob.mx/Paginas/SIM/Reportes/EnergiaGenerada.aspx'),
  ('wind_onshore','MX','Mexico',2022, 168, NULL, 'GWEC / CRE', 'https://www.cenace.gob.mx/Paginas/SIM/Reportes/EnergiaGenerada.aspx'),
  ('wind_onshore','MX','Mexico',2023,  150, NULL, 'GWEC / CRE', 'https://www.cenace.gob.mx/Paginas/SIM/Reportes/EnergiaGenerada.aspx'),
  ('wind_onshore','MX','Mexico',2024,  120, NULL, 'GWEC / CRE', 'https://www.cenace.gob.mx/Paginas/SIM/Reportes/EnergiaGenerada.aspx'),
  ('wind_onshore','MX','Mexico',2025,  200, NULL, 'GWEC / CRE', 'https://www.cenace.gob.mx/Paginas/SIM/Reportes/EnergiaGenerada.aspx'),

  -- Turkey (TEİAŞ / EPDK / TÜREB)
  ('wind_onshore','TR','Turkey',2006,   38, NULL, 'GWEC / TEIAS', 'https://www.teias.gov.tr/turkiye-elektrik-uretim-iletim-istatistikleri'),
  ('wind_onshore','TR','Turkey',2007,   60, NULL, 'GWEC / TEIAS', 'https://www.teias.gov.tr/turkiye-elektrik-uretim-iletim-istatistikleri'),
  ('wind_onshore','TR','Turkey',2008,  287, NULL, 'GWEC / TEIAS', 'https://www.teias.gov.tr/turkiye-elektrik-uretim-iletim-istatistikleri'),
  ('wind_onshore','TR','Turkey',2009,  342, NULL, 'GWEC / TEIAS', 'https://www.teias.gov.tr/turkiye-elektrik-uretim-iletim-istatistikleri'),
  ('wind_onshore','TR','Turkey',2010,  528, NULL, 'GWEC / TEIAS', 'https://www.teias.gov.tr/turkiye-elektrik-uretim-iletim-istatistikleri'),
  ('wind_onshore','TR','Turkey',2011,  470, NULL, 'GWEC / TEIAS', 'https://www.teias.gov.tr/turkiye-elektrik-uretim-iletim-istatistikleri'),
  ('wind_onshore','TR','Turkey',2012,  506, NULL, 'GWEC / TEIAS', 'https://www.teias.gov.tr/turkiye-elektrik-uretim-iletim-istatistikleri'),
  ('wind_onshore','TR','Turkey',2013,  646, NULL, 'GWEC / TEIAS', 'https://www.teias.gov.tr/turkiye-elektrik-uretim-iletim-istatistikleri'),
  ('wind_onshore','TR','Turkey',2014,  804, NULL, 'GWEC / TEIAS', 'https://www.teias.gov.tr/turkiye-elektrik-uretim-iletim-istatistikleri'),
  ('wind_onshore','TR','Turkey',2015, 956, NULL, 'GWEC / TEIAS', 'https://www.teias.gov.tr/turkiye-elektrik-uretim-iletim-istatistikleri'),
  ('wind_onshore','TR','Turkey',2016, 1387, NULL, 'GWEC / TEIAS', 'https://www.teias.gov.tr/turkiye-elektrik-uretim-iletim-istatistikleri'),
  ('wind_onshore','TR','Turkey',2017,  766, NULL, 'GWEC / TEIAS', 'https://www.teias.gov.tr/turkiye-elektrik-uretim-iletim-istatistikleri'),
  ('wind_onshore','TR','Turkey',2018,  497, NULL, 'GWEC / TEIAS', 'https://www.teias.gov.tr/turkiye-elektrik-uretim-iletim-istatistikleri'),
  ('wind_onshore','TR','Turkey',2019,  680, NULL, 'GWEC / TEIAS', 'https://www.teias.gov.tr/turkiye-elektrik-uretim-iletim-istatistikleri'),
  ('wind_onshore','TR','Turkey',2020, 1224, NULL, 'GWEC / TEIAS', 'https://www.teias.gov.tr/turkiye-elektrik-uretim-iletim-istatistikleri'),
  ('wind_onshore','TR','Turkey',2021, 1413, NULL, 'GWEC / TEIAS', 'https://www.teias.gov.tr/turkiye-elektrik-uretim-iletim-istatistikleri'),
  ('wind_onshore','TR','Turkey',2022, 905, NULL, 'GWEC / TEIAS', 'https://www.teias.gov.tr/turkiye-elektrik-uretim-iletim-istatistikleri'),
  ('wind_onshore','TR','Turkey',2023, 670, NULL, 'GWEC / TEIAS', 'https://www.teias.gov.tr/turkiye-elektrik-uretim-iletim-istatistikleri'),
  ('wind_onshore','TR','Turkey',2024, 850, NULL, 'GWEC / TEIAS', 'https://www.teias.gov.tr/turkiye-elektrik-uretim-iletim-istatistikleri'),
  ('wind_onshore','TR','Turkey',2025, 950, NULL, 'GWEC / TEIAS', 'https://www.teias.gov.tr/turkiye-elektrik-uretim-iletim-istatistikleri'),

-- ════════════════════════════════════════════════════════════════════════
-- WIND OFFSHORE — annual MW added (2000-2025)
-- ════════════════════════════════════════════════════════════════════════

  -- United Kingdom (BEIS REPD / TheCrownEstate / WindEurope)
  ('wind_offshore','GB','United Kingdom',2003,  60, NULL, 'WindEurope / BEIS REPD', 'https://www.gov.uk/government/publications/renewable-energy-planning-database-monthly-extract'),
  ('wind_offshore','GB','United Kingdom',2004,  60, NULL, 'WindEurope / BEIS REPD', 'https://www.gov.uk/government/publications/renewable-energy-planning-database-monthly-extract'),
  ('wind_offshore','GB','United Kingdom',2005,   0, NULL, 'WindEurope / BEIS REPD', 'https://www.gov.uk/government/publications/renewable-energy-planning-database-monthly-extract'),
  ('wind_offshore','GB','United Kingdom',2006,  90, NULL, 'WindEurope / BEIS REPD', 'https://www.gov.uk/government/publications/renewable-energy-planning-database-monthly-extract'),
  ('wind_offshore','GB','United Kingdom',2007,  90, NULL, 'WindEurope / BEIS REPD', 'https://www.gov.uk/government/publications/renewable-energy-planning-database-monthly-extract'),
  ('wind_offshore','GB','United Kingdom',2008, 195, NULL, 'WindEurope / BEIS REPD', 'https://www.gov.uk/government/publications/renewable-energy-planning-database-monthly-extract'),
  ('wind_offshore','GB','United Kingdom',2009, 285, NULL, 'WindEurope / BEIS REPD', 'https://www.gov.uk/government/publications/renewable-energy-planning-database-monthly-extract'),
  ('wind_offshore','GB','United Kingdom',2010, 651, NULL, 'WindEurope / BEIS REPD', 'https://www.gov.uk/government/publications/renewable-energy-planning-database-monthly-extract'),
  ('wind_offshore','GB','United Kingdom',2011, 752, NULL, 'WindEurope / BEIS REPD', 'https://www.gov.uk/government/publications/renewable-energy-planning-database-monthly-extract'),
  ('wind_offshore','GB','United Kingdom',2012, 854, NULL, 'WindEurope / BEIS REPD', 'https://www.gov.uk/government/publications/renewable-energy-planning-database-monthly-extract'),
  ('wind_offshore','GB','United Kingdom',2013, 733, NULL, 'WindEurope / BEIS REPD', 'https://www.gov.uk/government/publications/renewable-energy-planning-database-monthly-extract'),
  ('wind_offshore','GB','United Kingdom',2014, 813, NULL, 'WindEurope / BEIS REPD', 'https://www.gov.uk/government/publications/renewable-energy-planning-database-monthly-extract'),
  ('wind_offshore','GB','United Kingdom',2015, 566, NULL, 'WindEurope / BEIS REPD', 'https://www.gov.uk/government/publications/renewable-energy-planning-database-monthly-extract'),
  ('wind_offshore','GB','United Kingdom',2016,  56, NULL, 'WindEurope / BEIS REPD', 'https://www.gov.uk/government/publications/renewable-energy-planning-database-monthly-extract'),
  ('wind_offshore','GB','United Kingdom',2017, 1680, NULL, 'WindEurope / BEIS REPD', 'https://www.gov.uk/government/publications/renewable-energy-planning-database-monthly-extract'),
  ('wind_offshore','GB','United Kingdom',2018, 1312, NULL, 'WindEurope / BEIS REPD', 'https://www.gov.uk/government/publications/renewable-energy-planning-database-monthly-extract'),
  ('wind_offshore','GB','United Kingdom',2019, 1764, NULL, 'WindEurope / BEIS REPD', 'https://www.gov.uk/government/publications/renewable-energy-planning-database-monthly-extract'),
  ('wind_offshore','GB','United Kingdom',2020, 483, NULL, 'WindEurope / BEIS REPD', 'https://www.gov.uk/government/publications/renewable-energy-planning-database-monthly-extract'),
  ('wind_offshore','GB','United Kingdom',2021, 2317, NULL, 'WindEurope / BEIS REPD', 'https://www.gov.uk/government/publications/renewable-energy-planning-database-monthly-extract'),
  ('wind_offshore','GB','United Kingdom',2022, 1163, NULL, 'WindEurope / BEIS REPD', 'https://www.gov.uk/government/publications/renewable-energy-planning-database-monthly-extract'),
  ('wind_offshore','GB','United Kingdom',2023, 833, NULL, 'WindEurope / BEIS REPD', 'https://www.gov.uk/government/publications/renewable-energy-planning-database-monthly-extract'),
  ('wind_offshore','GB','United Kingdom',2024, 1200, NULL, 'WindEurope / BEIS REPD', 'https://www.gov.uk/government/publications/renewable-energy-planning-database-monthly-extract'),
  ('wind_offshore','GB','United Kingdom',2025, 1500, NULL, 'WindEurope / BEIS REPD', 'https://www.gov.uk/government/publications/renewable-energy-planning-database-monthly-extract'),

  -- Germany offshore (BSH / BNetzA / WindEurope)
  ('wind_offshore','DE','Germany',2009,  60, NULL, 'WindEurope / BSH', 'https://www.bsh.de/EN/TOPICS/Offshore/offshore_node.html'),
  ('wind_offshore','DE','Germany',2010,  48, NULL, 'WindEurope / BSH', 'https://www.bsh.de/EN/TOPICS/Offshore/offshore_node.html'),
  ('wind_offshore','DE','Germany',2011,  108, NULL, 'WindEurope / BSH', 'https://www.bsh.de/EN/TOPICS/Offshore/offshore_node.html'),
  ('wind_offshore','DE','Germany',2012,  80, NULL, 'WindEurope / BSH', 'https://www.bsh.de/EN/TOPICS/Offshore/offshore_node.html'),
  ('wind_offshore','DE','Germany',2013,  240, NULL, 'WindEurope / BSH', 'https://www.bsh.de/EN/TOPICS/Offshore/offshore_node.html'),
  ('wind_offshore','DE','Germany',2014, 1438, NULL, 'WindEurope / BSH', 'https://www.bsh.de/EN/TOPICS/Offshore/offshore_node.html'),
  ('wind_offshore','DE','Germany',2015, 2282, NULL, 'WindEurope / BSH', 'https://www.bsh.de/EN/TOPICS/Offshore/offshore_node.html'),
  ('wind_offshore','DE','Germany',2016, 818, NULL, 'WindEurope / BSH', 'https://www.bsh.de/EN/TOPICS/Offshore/offshore_node.html'),
  ('wind_offshore','DE','Germany',2017, 1247, NULL, 'WindEurope / BSH', 'https://www.bsh.de/EN/TOPICS/Offshore/offshore_node.html'),
  ('wind_offshore','DE','Germany',2018, 969, NULL, 'WindEurope / BSH', 'https://www.bsh.de/EN/TOPICS/Offshore/offshore_node.html'),
  ('wind_offshore','DE','Germany',2019, 1111, NULL, 'WindEurope / BSH', 'https://www.bsh.de/EN/TOPICS/Offshore/offshore_node.html'),
  ('wind_offshore','DE','Germany',2020, 219, NULL, 'WindEurope / BSH', 'https://www.bsh.de/EN/TOPICS/Offshore/offshore_node.html'),
  ('wind_offshore','DE','Germany',2021,    0, NULL, 'WindEurope / BSH', 'https://www.bsh.de/EN/TOPICS/Offshore/offshore_node.html'),
  ('wind_offshore','DE','Germany',2022, 342, NULL, 'WindEurope / BSH', 'https://www.bsh.de/EN/TOPICS/Offshore/offshore_node.html'),
  ('wind_offshore','DE','Germany',2023, 257, NULL, 'WindEurope / BSH', 'https://www.bsh.de/EN/TOPICS/Offshore/offshore_node.html'),
  ('wind_offshore','DE','Germany',2024, 730, NULL, 'WindEurope / BSH', 'https://www.bsh.de/EN/TOPICS/Offshore/offshore_node.html'),
  ('wind_offshore','DE','Germany',2025, 1100, NULL, 'WindEurope / BSH', 'https://www.bsh.de/EN/TOPICS/Offshore/offshore_node.html'),

  -- Netherlands offshore
  ('wind_offshore','NL','Netherlands',2007, 108, NULL, 'WindEurope / RVO', 'https://www.rvo.nl/onderwerpen/windenergie-op-zee'),
  ('wind_offshore','NL','Netherlands',2008,   0, NULL, 'WindEurope / RVO', 'https://www.rvo.nl/onderwerpen/windenergie-op-zee'),
  ('wind_offshore','NL','Netherlands',2009, 120, NULL, 'WindEurope / RVO', 'https://www.rvo.nl/onderwerpen/windenergie-op-zee'),
  ('wind_offshore','NL','Netherlands',2014,    0, NULL, 'WindEurope / RVO', 'https://www.rvo.nl/onderwerpen/windenergie-op-zee'),
  ('wind_offshore','NL','Netherlands',2015,  129, NULL, 'WindEurope / RVO', 'https://www.rvo.nl/onderwerpen/windenergie-op-zee'),
  ('wind_offshore','NL','Netherlands',2016,    0, NULL, 'WindEurope / RVO', 'https://www.rvo.nl/onderwerpen/windenergie-op-zee'),
  ('wind_offshore','NL','Netherlands',2017,    0, NULL, 'WindEurope / RVO', 'https://www.rvo.nl/onderwerpen/windenergie-op-zee'),
  ('wind_offshore','NL','Netherlands',2018,    0, NULL, 'WindEurope / RVO', 'https://www.rvo.nl/onderwerpen/windenergie-op-zee'),
  ('wind_offshore','NL','Netherlands',2019, 1118, NULL, 'WindEurope / RVO', 'https://www.rvo.nl/onderwerpen/windenergie-op-zee'),
  ('wind_offshore','NL','Netherlands',2020,    0, NULL, 'WindEurope / RVO', 'https://www.rvo.nl/onderwerpen/windenergie-op-zee'),
  ('wind_offshore','NL','Netherlands',2021,  392, NULL, 'WindEurope / RVO', 'https://www.rvo.nl/onderwerpen/windenergie-op-zee'),
  ('wind_offshore','NL','Netherlands',2022, 1521, NULL, 'WindEurope / RVO', 'https://www.rvo.nl/onderwerpen/windenergie-op-zee'),
  ('wind_offshore','NL','Netherlands',2023,  759, NULL, 'WindEurope / RVO', 'https://www.rvo.nl/onderwerpen/windenergie-op-zee'),
  ('wind_offshore','NL','Netherlands',2024, 1500, NULL, 'WindEurope / RVO', 'https://www.rvo.nl/onderwerpen/windenergie-op-zee'),
  ('wind_offshore','NL','Netherlands',2025, 1700, NULL, 'WindEurope / RVO', 'https://www.rvo.nl/onderwerpen/windenergie-op-zee'),

  -- Denmark offshore
  ('wind_offshore','DK','Denmark',2002, 160, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_offshore','DK','Denmark',2003, 165, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_offshore','DK','Denmark',2009, 230, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_offshore','DK','Denmark',2010, 207, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_offshore','DK','Denmark',2012, 400, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_offshore','DK','Denmark',2013, 400, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_offshore','DK','Denmark',2017, 28, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_offshore','DK','Denmark',2018, 406, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_offshore','DK','Denmark',2019, 374, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_offshore','DK','Denmark',2021,  605, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_offshore','DK','Denmark',2022,  342, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_offshore','DK','Denmark',2023,    0, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_offshore','DK','Denmark',2024,  300, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),
  ('wind_offshore','DK','Denmark',2025,  500, NULL, 'WindEurope / Energistyrelsen', 'https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/register-wind-turbines'),

  -- Belgium offshore
  ('wind_offshore','BE','Belgium',2009,  30, NULL, 'WindEurope / FPS Economy', 'https://economie.fgov.be/en/themes/energy/sources-energy/renewable-energy/wind-energy'),
  ('wind_offshore','BE','Belgium',2010,   0, NULL, 'WindEurope / FPS Economy', 'https://economie.fgov.be/en/themes/energy/sources-energy/renewable-energy/wind-energy'),
  ('wind_offshore','BE','Belgium',2011, 165, NULL, 'WindEurope / FPS Economy', 'https://economie.fgov.be/en/themes/energy/sources-energy/renewable-energy/wind-energy'),
  ('wind_offshore','BE','Belgium',2012, 165, NULL, 'WindEurope / FPS Economy', 'https://economie.fgov.be/en/themes/energy/sources-energy/renewable-energy/wind-energy'),
  ('wind_offshore','BE','Belgium',2013, 192, NULL, 'WindEurope / FPS Economy', 'https://economie.fgov.be/en/themes/energy/sources-energy/renewable-energy/wind-energy'),
  ('wind_offshore','BE','Belgium',2017,  165, NULL, 'WindEurope / FPS Economy', 'https://economie.fgov.be/en/themes/energy/sources-energy/renewable-energy/wind-energy'),
  ('wind_offshore','BE','Belgium',2018,  308, NULL, 'WindEurope / FPS Economy', 'https://economie.fgov.be/en/themes/energy/sources-energy/renewable-energy/wind-energy'),
  ('wind_offshore','BE','Belgium',2019,  370, NULL, 'WindEurope / FPS Economy', 'https://economie.fgov.be/en/themes/energy/sources-energy/renewable-energy/wind-energy'),
  ('wind_offshore','BE','Belgium',2020,  706, NULL, 'WindEurope / FPS Economy', 'https://economie.fgov.be/en/themes/energy/sources-energy/renewable-energy/wind-energy'),
  ('wind_offshore','BE','Belgium',2021,    0, NULL, 'WindEurope / FPS Economy', 'https://economie.fgov.be/en/themes/energy/sources-energy/renewable-energy/wind-energy'),
  ('wind_offshore','BE','Belgium',2022,    0, NULL, 'WindEurope / FPS Economy', 'https://economie.fgov.be/en/themes/energy/sources-energy/renewable-energy/wind-energy'),
  ('wind_offshore','BE','Belgium',2023,    0, NULL, 'WindEurope / FPS Economy', 'https://economie.fgov.be/en/themes/energy/sources-energy/renewable-energy/wind-energy'),
  ('wind_offshore','BE','Belgium',2024,    0, NULL, 'WindEurope / FPS Economy', 'https://economie.fgov.be/en/themes/energy/sources-energy/renewable-energy/wind-energy'),
  ('wind_offshore','BE','Belgium',2025,    0, NULL, 'WindEurope / FPS Economy', 'https://economie.fgov.be/en/themes/energy/sources-energy/renewable-energy/wind-energy'),

  -- US offshore (BOEM)
  ('wind_offshore','US','United States',2016,  30, NULL, 'BOEM', 'https://www.boem.gov/renewable-energy'),
  ('wind_offshore','US','United States',2020,   0, NULL, 'BOEM', 'https://www.boem.gov/renewable-energy'),
  ('wind_offshore','US','United States',2021,   0, NULL, 'BOEM', 'https://www.boem.gov/renewable-energy'),
  ('wind_offshore','US','United States',2022,  12, NULL, 'BOEM', 'https://www.boem.gov/renewable-energy'),
  ('wind_offshore','US','United States',2023, 174, NULL, 'BOEM', 'https://www.boem.gov/renewable-energy'),
  ('wind_offshore','US','United States',2024, 750, NULL, 'BOEM', 'https://www.boem.gov/renewable-energy'),
  ('wind_offshore','US','United States',2025, 900, NULL, 'BOEM', 'https://www.boem.gov/renewable-energy'),

  -- Taiwan offshore (MoEA Bureau of Energy)
  ('wind_offshore','TW','Taiwan',2017,    8, NULL, 'Taiwan MoEA', 'https://www.moeaboe.gov.tw/ECW/english/content/Content.aspx?menu_id=1540'),
  ('wind_offshore','TW','Taiwan',2019, 120, NULL, 'Taiwan MoEA', 'https://www.moeaboe.gov.tw/ECW/english/content/Content.aspx?menu_id=1540'),
  ('wind_offshore','TW','Taiwan',2021, 109, NULL, 'Taiwan MoEA', 'https://www.moeaboe.gov.tw/ECW/english/content/Content.aspx?menu_id=1540'),
  ('wind_offshore','TW','Taiwan',2022,  237, NULL, 'Taiwan MoEA', 'https://www.moeaboe.gov.tw/ECW/english/content/Content.aspx?menu_id=1540'),
  ('wind_offshore','TW','Taiwan',2023, 750, NULL, 'Taiwan MoEA', 'https://www.moeaboe.gov.tw/ECW/english/content/Content.aspx?menu_id=1540'),
  ('wind_offshore','TW','Taiwan',2024, 700, NULL, 'Taiwan MoEA', 'https://www.moeaboe.gov.tw/ECW/english/content/Content.aspx?menu_id=1540'),
  ('wind_offshore','TW','Taiwan',2025, 900, NULL, 'Taiwan MoEA', 'https://www.moeaboe.gov.tw/ECW/english/content/Content.aspx?menu_id=1540'),

  -- France offshore (RTE / SDES — first commercial OFW commissioned 2022)
  ('wind_offshore','FR','France',2022, 480, NULL, 'WindEurope / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('wind_offshore','FR','France',2023, 480, NULL, 'WindEurope / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('wind_offshore','FR','France',2024, 500, NULL, 'WindEurope / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('wind_offshore','FR','France',2025, 600, NULL, 'WindEurope / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),

-- ════════════════════════════════════════════════════════════════════════
-- SOLAR PV — annual MW added (2010-2025)
-- ════════════════════════════════════════════════════════════════════════

  -- Germany (BNetzA / BMWi)
  ('solar','DE','Germany',2010, 7408, NULL, 'IEA-PVPS / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('solar','DE','Germany',2011, 7485, NULL, 'IEA-PVPS / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('solar','DE','Germany',2012, 7604, NULL, 'IEA-PVPS / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('solar','DE','Germany',2013, 3304, NULL, 'IEA-PVPS / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('solar','DE','Germany',2014, 1899, NULL, 'IEA-PVPS / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('solar','DE','Germany',2015, 1462, NULL, 'IEA-PVPS / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('solar','DE','Germany',2016, 1525, NULL, 'IEA-PVPS / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('solar','DE','Germany',2017, 1750, NULL, 'IEA-PVPS / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('solar','DE','Germany',2018, 2960, NULL, 'IEA-PVPS / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('solar','DE','Germany',2019, 3884, NULL, 'IEA-PVPS / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('solar','DE','Germany',2020, 4882, NULL, 'IEA-PVPS / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('solar','DE','Germany',2021, 5300, NULL, 'IEA-PVPS / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('solar','DE','Germany',2022, 7440, NULL, 'IEA-PVPS / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('solar','DE','Germany',2023, 14280, NULL, 'IEA-PVPS / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('solar','DE','Germany',2024, 16200, NULL, 'IEA-PVPS / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),
  ('solar','DE','Germany',2025, 14000, NULL, 'IEA-PVPS / BNetzA', 'https://www.marktstammdatenregister.de/MaStR'),

  -- Spain (REE / IDAE / UNEF)
  ('solar','ES','Spain',2010, 370, NULL, 'IEA-PVPS / REE', 'https://www.ree.es/en/datos/generation'),
  ('solar','ES','Spain',2011, 354, NULL, 'IEA-PVPS / REE', 'https://www.ree.es/en/datos/generation'),
  ('solar','ES','Spain',2012, 276, NULL, 'IEA-PVPS / REE', 'https://www.ree.es/en/datos/generation'),
  ('solar','ES','Spain',2013, 140, NULL, 'IEA-PVPS / REE', 'https://www.ree.es/en/datos/generation'),
  ('solar','ES','Spain',2014,  22, NULL, 'IEA-PVPS / REE', 'https://www.ree.es/en/datos/generation'),
  ('solar','ES','Spain',2015,  56, NULL, 'IEA-PVPS / REE', 'https://www.ree.es/en/datos/generation'),
  ('solar','ES','Spain',2016,  55, NULL, 'IEA-PVPS / REE', 'https://www.ree.es/en/datos/generation'),
  ('solar','ES','Spain',2017, 135, NULL, 'IEA-PVPS / REE', 'https://www.ree.es/en/datos/generation'),
  ('solar','ES','Spain',2018, 135, NULL, 'IEA-PVPS / REE', 'https://www.ree.es/en/datos/generation'),
  ('solar','ES','Spain',2019, 4751, NULL, 'IEA-PVPS / REE', 'https://www.ree.es/en/datos/generation'),
  ('solar','ES','Spain',2020, 3015, NULL, 'IEA-PVPS / REE', 'https://www.ree.es/en/datos/generation'),
  ('solar','ES','Spain',2021, 4370, NULL, 'IEA-PVPS / REE', 'https://www.ree.es/en/datos/generation'),
  ('solar','ES','Spain',2022, 4685, NULL, 'IEA-PVPS / REE', 'https://www.ree.es/en/datos/generation'),
  ('solar','ES','Spain',2023, 5594, NULL, 'IEA-PVPS / REE', 'https://www.ree.es/en/datos/generation'),
  ('solar','ES','Spain',2024, 5800, NULL, 'IEA-PVPS / REE', 'https://www.ree.es/en/datos/generation'),
  ('solar','ES','Spain',2025, 5000, NULL, 'IEA-PVPS / REE', 'https://www.ree.es/en/datos/generation'),

  -- Italy (Terna / GSE)
  ('solar','IT','Italy',2010, 2326, NULL, 'IEA-PVPS / GSE', 'https://www.gse.it/dati-e-scenari/statistiche'),
  ('solar','IT','Italy',2011, 9454, NULL, 'IEA-PVPS / GSE', 'https://www.gse.it/dati-e-scenari/statistiche'),
  ('solar','IT','Italy',2012, 3535, NULL, 'IEA-PVPS / GSE', 'https://www.gse.it/dati-e-scenari/statistiche'),
  ('solar','IT','Italy',2013, 1364, NULL, 'IEA-PVPS / GSE', 'https://www.gse.it/dati-e-scenari/statistiche'),
  ('solar','IT','Italy',2014, 385, NULL, 'IEA-PVPS / GSE', 'https://www.gse.it/dati-e-scenari/statistiche'),
  ('solar','IT','Italy',2015, 300, NULL, 'IEA-PVPS / GSE', 'https://www.gse.it/dati-e-scenari/statistiche'),
  ('solar','IT','Italy',2016, 369, NULL, 'IEA-PVPS / GSE', 'https://www.gse.it/dati-e-scenari/statistiche'),
  ('solar','IT','Italy',2017, 414, NULL, 'IEA-PVPS / GSE', 'https://www.gse.it/dati-e-scenari/statistiche'),
  ('solar','IT','Italy',2018, 437, NULL, 'IEA-PVPS / GSE', 'https://www.gse.it/dati-e-scenari/statistiche'),
  ('solar','IT','Italy',2019, 750, NULL, 'IEA-PVPS / GSE', 'https://www.gse.it/dati-e-scenari/statistiche'),
  ('solar','IT','Italy',2020, 781, NULL, 'IEA-PVPS / GSE', 'https://www.gse.it/dati-e-scenari/statistiche'),
  ('solar','IT','Italy',2021, 935, NULL, 'IEA-PVPS / GSE', 'https://www.gse.it/dati-e-scenari/statistiche'),
  ('solar','IT','Italy',2022, 2480, NULL, 'IEA-PVPS / GSE', 'https://www.gse.it/dati-e-scenari/statistiche'),
  ('solar','IT','Italy',2023, 5234, NULL, 'IEA-PVPS / GSE', 'https://www.gse.it/dati-e-scenari/statistiche'),
  ('solar','IT','Italy',2024, 6800, NULL, 'IEA-PVPS / GSE', 'https://www.gse.it/dati-e-scenari/statistiche'),
  ('solar','IT','Italy',2025, 6500, NULL, 'IEA-PVPS / GSE', 'https://www.gse.it/dati-e-scenari/statistiche'),

  -- France (RTE / SDES)
  ('solar','FR','France',2010, 720, NULL, 'IEA-PVPS / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('solar','FR','France',2011, 1690, NULL, 'IEA-PVPS / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('solar','FR','France',2012, 1115, NULL, 'IEA-PVPS / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('solar','FR','France',2013, 613, NULL, 'IEA-PVPS / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('solar','FR','France',2014, 927, NULL, 'IEA-PVPS / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('solar','FR','France',2015, 879, NULL, 'IEA-PVPS / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('solar','FR','France',2016, 559, NULL, 'IEA-PVPS / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('solar','FR','France',2017, 887, NULL, 'IEA-PVPS / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('solar','FR','France',2018, 873, NULL, 'IEA-PVPS / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('solar','FR','France',2019, 924, NULL, 'IEA-PVPS / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('solar','FR','France',2020, 911, NULL, 'IEA-PVPS / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('solar','FR','France',2021, 2680, NULL, 'IEA-PVPS / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('solar','FR','France',2022, 2696, NULL, 'IEA-PVPS / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('solar','FR','France',2023, 3174, NULL, 'IEA-PVPS / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('solar','FR','France',2024, 4700, NULL, 'IEA-PVPS / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),
  ('solar','FR','France',2025, 5000, NULL, 'IEA-PVPS / RTE', 'https://www.rte-france.com/en/eco2mix/eco2mix-mix-energetique'),

  -- United Kingdom (DUKES / Solar Energy UK)
  ('solar','GB','United Kingdom',2010, 41, NULL, 'IEA-PVPS / DUKES', 'https://www.gov.uk/government/statistics/digest-of-uk-energy-statistics-dukes-2024'),
  ('solar','GB','United Kingdom',2011, 909, NULL, 'IEA-PVPS / DUKES', 'https://www.gov.uk/government/statistics/digest-of-uk-energy-statistics-dukes-2024'),
  ('solar','GB','United Kingdom',2012, 791, NULL, 'IEA-PVPS / DUKES', 'https://www.gov.uk/government/statistics/digest-of-uk-energy-statistics-dukes-2024'),
  ('solar','GB','United Kingdom',2013, 1463, NULL, 'IEA-PVPS / DUKES', 'https://www.gov.uk/government/statistics/digest-of-uk-energy-statistics-dukes-2024'),
  ('solar','GB','United Kingdom',2014, 2469, NULL, 'IEA-PVPS / DUKES', 'https://www.gov.uk/government/statistics/digest-of-uk-energy-statistics-dukes-2024'),
  ('solar','GB','United Kingdom',2015, 4091, NULL, 'IEA-PVPS / DUKES', 'https://www.gov.uk/government/statistics/digest-of-uk-energy-statistics-dukes-2024'),
  ('solar','GB','United Kingdom',2016, 1971, NULL, 'IEA-PVPS / DUKES', 'https://www.gov.uk/government/statistics/digest-of-uk-energy-statistics-dukes-2024'),
  ('solar','GB','United Kingdom',2017, 953, NULL, 'IEA-PVPS / DUKES', 'https://www.gov.uk/government/statistics/digest-of-uk-energy-statistics-dukes-2024'),
  ('solar','GB','United Kingdom',2018, 277, NULL, 'IEA-PVPS / DUKES', 'https://www.gov.uk/government/statistics/digest-of-uk-energy-statistics-dukes-2024'),
  ('solar','GB','United Kingdom',2019, 233, NULL, 'IEA-PVPS / DUKES', 'https://www.gov.uk/government/statistics/digest-of-uk-energy-statistics-dukes-2024'),
  ('solar','GB','United Kingdom',2020, 545, NULL, 'IEA-PVPS / DUKES', 'https://www.gov.uk/government/statistics/digest-of-uk-energy-statistics-dukes-2024'),
  ('solar','GB','United Kingdom',2021, 730, NULL, 'IEA-PVPS / DUKES', 'https://www.gov.uk/government/statistics/digest-of-uk-energy-statistics-dukes-2024'),
  ('solar','GB','United Kingdom',2022, 779, NULL, 'IEA-PVPS / DUKES', 'https://www.gov.uk/government/statistics/digest-of-uk-energy-statistics-dukes-2024'),
  ('solar','GB','United Kingdom',2023, 1289, NULL, 'IEA-PVPS / DUKES', 'https://www.gov.uk/government/statistics/digest-of-uk-energy-statistics-dukes-2024'),
  ('solar','GB','United Kingdom',2024, 1900, NULL, 'IEA-PVPS / DUKES', 'https://www.gov.uk/government/statistics/digest-of-uk-energy-statistics-dukes-2024'),
  ('solar','GB','United Kingdom',2025, 2400, NULL, 'IEA-PVPS / DUKES', 'https://www.gov.uk/government/statistics/digest-of-uk-energy-statistics-dukes-2024'),

  -- Netherlands (CBS / RVO)
  ('solar','NL','Netherlands',2010,  21, NULL, 'IEA-PVPS / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('solar','NL','Netherlands',2011,  58, NULL, 'IEA-PVPS / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('solar','NL','Netherlands',2012, 195, NULL, 'IEA-PVPS / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('solar','NL','Netherlands',2013, 374, NULL, 'IEA-PVPS / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('solar','NL','Netherlands',2014, 351, NULL, 'IEA-PVPS / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('solar','NL','Netherlands',2015, 461, NULL, 'IEA-PVPS / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('solar','NL','Netherlands',2016, 525, NULL, 'IEA-PVPS / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('solar','NL','Netherlands',2017, 769, NULL, 'IEA-PVPS / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('solar','NL','Netherlands',2018, 1614, NULL, 'IEA-PVPS / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('solar','NL','Netherlands',2019, 2402, NULL, 'IEA-PVPS / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('solar','NL','Netherlands',2020, 3286, NULL, 'IEA-PVPS / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('solar','NL','Netherlands',2021, 3572, NULL, 'IEA-PVPS / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('solar','NL','Netherlands',2022, 4144, NULL, 'IEA-PVPS / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('solar','NL','Netherlands',2023, 4317, NULL, 'IEA-PVPS / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('solar','NL','Netherlands',2024, 3300, NULL, 'IEA-PVPS / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),
  ('solar','NL','Netherlands',2025, 3000, NULL, 'IEA-PVPS / CBS', 'https://www.cbs.nl/en-gb/figures/detail/82610ENG'),

  -- Belgium (APERe / Elia)
  ('solar','BE','Belgium',2010, 424, NULL, 'IEA-PVPS / APERe', 'https://www.apere.org/en/observatory'),
  ('solar','BE','Belgium',2011, 974, NULL, 'IEA-PVPS / APERe', 'https://www.apere.org/en/observatory'),
  ('solar','BE','Belgium',2012, 599, NULL, 'IEA-PVPS / APERe', 'https://www.apere.org/en/observatory'),
  ('solar','BE','Belgium',2013, 215, NULL, 'IEA-PVPS / APERe', 'https://www.apere.org/en/observatory'),
  ('solar','BE','Belgium',2014, 65, NULL, 'IEA-PVPS / APERe', 'https://www.apere.org/en/observatory'),
  ('solar','BE','Belgium',2015, 95, NULL, 'IEA-PVPS / APERe', 'https://www.apere.org/en/observatory'),
  ('solar','BE','Belgium',2016, 169, NULL, 'IEA-PVPS / APERe', 'https://www.apere.org/en/observatory'),
  ('solar','BE','Belgium',2017, 285, NULL, 'IEA-PVPS / APERe', 'https://www.apere.org/en/observatory'),
  ('solar','BE','Belgium',2018, 343, NULL, 'IEA-PVPS / APERe', 'https://www.apere.org/en/observatory'),
  ('solar','BE','Belgium',2019, 575, NULL, 'IEA-PVPS / APERe', 'https://www.apere.org/en/observatory'),
  ('solar','BE','Belgium',2020, 1086, NULL, 'IEA-PVPS / APERe', 'https://www.apere.org/en/observatory'),
  ('solar','BE','Belgium',2021, 988, NULL, 'IEA-PVPS / APERe', 'https://www.apere.org/en/observatory'),
  ('solar','BE','Belgium',2022, 1453, NULL, 'IEA-PVPS / APERe', 'https://www.apere.org/en/observatory'),
  ('solar','BE','Belgium',2023, 1817, NULL, 'IEA-PVPS / APERe', 'https://www.apere.org/en/observatory'),
  ('solar','BE','Belgium',2024, 1700, NULL, 'IEA-PVPS / APERe', 'https://www.apere.org/en/observatory'),
  ('solar','BE','Belgium',2025, 1500, NULL, 'IEA-PVPS / APERe', 'https://www.apere.org/en/observatory'),

  -- Australia (Clean Energy Regulator / AEMO)
  ('solar','AU','Australia',2010, 384, NULL, 'IEA-PVPS / CER', 'https://www.cleanenergyregulator.gov.au/RET/Pages/About%20the%20Renewable%20Energy%20Target/Renewable-Energy-Target.aspx'),
  ('solar','AU','Australia',2011, 837, NULL, 'IEA-PVPS / CER', 'https://www.cleanenergyregulator.gov.au/RET/Pages/About%20the%20Renewable%20Energy%20Target/Renewable-Energy-Target.aspx'),
  ('solar','AU','Australia',2012, 1037, NULL, 'IEA-PVPS / CER', 'https://www.cleanenergyregulator.gov.au/RET/Pages/About%20the%20Renewable%20Energy%20Target/Renewable-Energy-Target.aspx'),
  ('solar','AU','Australia',2013, 848, NULL, 'IEA-PVPS / CER', 'https://www.cleanenergyregulator.gov.au/RET/Pages/About%20the%20Renewable%20Energy%20Target/Renewable-Energy-Target.aspx'),
  ('solar','AU','Australia',2014, 854, NULL, 'IEA-PVPS / CER', 'https://www.cleanenergyregulator.gov.au/RET/Pages/About%20the%20Renewable%20Energy%20Target/Renewable-Energy-Target.aspx'),
  ('solar','AU','Australia',2015, 935, NULL, 'IEA-PVPS / CER', 'https://www.cleanenergyregulator.gov.au/RET/Pages/About%20the%20Renewable%20Energy%20Target/Renewable-Energy-Target.aspx'),
  ('solar','AU','Australia',2016, 836, NULL, 'IEA-PVPS / CER', 'https://www.cleanenergyregulator.gov.au/RET/Pages/About%20the%20Renewable%20Energy%20Target/Renewable-Energy-Target.aspx'),
  ('solar','AU','Australia',2017, 1257, NULL, 'IEA-PVPS / CER', 'https://www.cleanenergyregulator.gov.au/RET/Pages/About%20the%20Renewable%20Energy%20Target/Renewable-Energy-Target.aspx'),
  ('solar','AU','Australia',2018, 3775, NULL, 'IEA-PVPS / CER', 'https://www.cleanenergyregulator.gov.au/RET/Pages/About%20the%20Renewable%20Energy%20Target/Renewable-Energy-Target.aspx'),
  ('solar','AU','Australia',2019, 6300, NULL, 'IEA-PVPS / CER', 'https://www.cleanenergyregulator.gov.au/RET/Pages/About%20the%20Renewable%20Energy%20Target/Renewable-Energy-Target.aspx'),
  ('solar','AU','Australia',2020, 5070, NULL, 'IEA-PVPS / CER', 'https://www.cleanenergyregulator.gov.au/RET/Pages/About%20the%20Renewable%20Energy%20Target/Renewable-Energy-Target.aspx'),
  ('solar','AU','Australia',2021, 4800, NULL, 'IEA-PVPS / CER', 'https://www.cleanenergyregulator.gov.au/RET/Pages/About%20the%20Renewable%20Energy%20Target/Renewable-Energy-Target.aspx'),
  ('solar','AU','Australia',2022, 4250, NULL, 'IEA-PVPS / CER', 'https://www.cleanenergyregulator.gov.au/RET/Pages/About%20the%20Renewable%20Energy%20Target/Renewable-Energy-Target.aspx'),
  ('solar','AU','Australia',2023, 4500, NULL, 'IEA-PVPS / CER', 'https://www.cleanenergyregulator.gov.au/RET/Pages/About%20the%20Renewable%20Energy%20Target/Renewable-Energy-Target.aspx'),
  ('solar','AU','Australia',2024, 4900, NULL, 'IEA-PVPS / CER', 'https://www.cleanenergyregulator.gov.au/RET/Pages/About%20the%20Renewable%20Energy%20Target/Renewable-Energy-Target.aspx'),
  ('solar','AU','Australia',2025, 5500, NULL, 'IEA-PVPS / CER', 'https://www.cleanenergyregulator.gov.au/RET/Pages/About%20the%20Renewable%20Energy%20Target/Renewable-Energy-Target.aspx'),

  -- Japan (METI / ANRE FIT register)
  ('solar','JP','Japan',2010, 991, NULL, 'IEA-PVPS / METI', 'https://www.enecho.meti.go.jp/category/saving_and_new/saiene/statistics/'),
  ('solar','JP','Japan',2011, 1296, NULL, 'IEA-PVPS / METI', 'https://www.enecho.meti.go.jp/category/saving_and_new/saiene/statistics/'),
  ('solar','JP','Japan',2012, 2000, NULL, 'IEA-PVPS / METI', 'https://www.enecho.meti.go.jp/category/saving_and_new/saiene/statistics/'),
  ('solar','JP','Japan',2013, 6900, NULL, 'IEA-PVPS / METI', 'https://www.enecho.meti.go.jp/category/saving_and_new/saiene/statistics/'),
  ('solar','JP','Japan',2014, 9700, NULL, 'IEA-PVPS / METI', 'https://www.enecho.meti.go.jp/category/saving_and_new/saiene/statistics/'),
  ('solar','JP','Japan',2015, 10800, NULL, 'IEA-PVPS / METI', 'https://www.enecho.meti.go.jp/category/saving_and_new/saiene/statistics/'),
  ('solar','JP','Japan',2016, 8600, NULL, 'IEA-PVPS / METI', 'https://www.enecho.meti.go.jp/category/saving_and_new/saiene/statistics/'),
  ('solar','JP','Japan',2017, 7000, NULL, 'IEA-PVPS / METI', 'https://www.enecho.meti.go.jp/category/saving_and_new/saiene/statistics/'),
  ('solar','JP','Japan',2018, 6500, NULL, 'IEA-PVPS / METI', 'https://www.enecho.meti.go.jp/category/saving_and_new/saiene/statistics/'),
  ('solar','JP','Japan',2019, 7000, NULL, 'IEA-PVPS / METI', 'https://www.enecho.meti.go.jp/category/saving_and_new/saiene/statistics/'),
  ('solar','JP','Japan',2020, 6700, NULL, 'IEA-PVPS / METI', 'https://www.enecho.meti.go.jp/category/saving_and_new/saiene/statistics/'),
  ('solar','JP','Japan',2021, 6500, NULL, 'IEA-PVPS / METI', 'https://www.enecho.meti.go.jp/category/saving_and_new/saiene/statistics/'),
  ('solar','JP','Japan',2022, 6500, NULL, 'IEA-PVPS / METI', 'https://www.enecho.meti.go.jp/category/saving_and_new/saiene/statistics/'),
  ('solar','JP','Japan',2023, 6200, NULL, 'IEA-PVPS / METI', 'https://www.enecho.meti.go.jp/category/saving_and_new/saiene/statistics/'),
  ('solar','JP','Japan',2024, 6000, NULL, 'IEA-PVPS / METI', 'https://www.enecho.meti.go.jp/category/saving_and_new/saiene/statistics/'),
  ('solar','JP','Japan',2025, 6500, NULL, 'IEA-PVPS / METI', 'https://www.enecho.meti.go.jp/category/saving_and_new/saiene/statistics/'),

  -- United States (EIA Form 860 + SEIA-Wood Mac US Solar Market Insight)
  ('solar','US','United States',2010, 919, NULL, 'EIA / IEA-PVPS', 'https://www.eia.gov/electricity/data/eia860/'),
  ('solar','US','United States',2011, 1855, NULL, 'EIA / IEA-PVPS', 'https://www.eia.gov/electricity/data/eia860/'),
  ('solar','US','United States',2012, 3373, NULL, 'EIA / IEA-PVPS', 'https://www.eia.gov/electricity/data/eia860/'),
  ('solar','US','United States',2013, 4776, NULL, 'EIA / IEA-PVPS', 'https://www.eia.gov/electricity/data/eia860/'),
  ('solar','US','United States',2014, 6201, NULL, 'EIA / IEA-PVPS', 'https://www.eia.gov/electricity/data/eia860/'),
  ('solar','US','United States',2015, 7493, NULL, 'EIA / IEA-PVPS', 'https://www.eia.gov/electricity/data/eia860/'),
  ('solar','US','United States',2016, 14761, NULL, 'EIA / IEA-PVPS', 'https://www.eia.gov/electricity/data/eia860/'),
  ('solar','US','United States',2017, 10608, NULL, 'EIA / IEA-PVPS', 'https://www.eia.gov/electricity/data/eia860/'),
  ('solar','US','United States',2018, 10600, NULL, 'EIA / IEA-PVPS', 'https://www.eia.gov/electricity/data/eia860/'),
  ('solar','US','United States',2019, 13300, NULL, 'EIA / IEA-PVPS', 'https://www.eia.gov/electricity/data/eia860/'),
  ('solar','US','United States',2020, 19200, NULL, 'EIA / IEA-PVPS', 'https://www.eia.gov/electricity/data/eia860/'),
  ('solar','US','United States',2021, 23600, NULL, 'EIA / IEA-PVPS', 'https://www.eia.gov/electricity/data/eia860/'),
  ('solar','US','United States',2022, 20200, NULL, 'EIA / IEA-PVPS', 'https://www.eia.gov/electricity/data/eia860/'),
  ('solar','US','United States',2023, 33000, NULL, 'EIA / IEA-PVPS', 'https://www.eia.gov/electricity/data/eia860/'),
  ('solar','US','United States',2024, 50000, NULL, 'EIA / IEA-PVPS', 'https://www.eia.gov/electricity/data/eia860/'),
  ('solar','US','United States',2025, 47000, NULL, 'EIA / IEA-PVPS', 'https://www.eia.gov/electricity/data/eia860/'),

-- ════════════════════════════════════════════════════════════════════════
-- BESS — annual MW added + average duration_h (2018-2025)
-- ════════════════════════════════════════════════════════════════════════

  -- United Kingdom (Modo Energy / National Grid ESO / RenewableUK)
  ('bess','GB','United Kingdom',2018, 250, 0.6, 'Modo Energy / RenewableUK', 'https://modoenergy.com/research/gb-bess-tracker'),
  ('bess','GB','United Kingdom',2019, 200, 0.7, 'Modo Energy / RenewableUK', 'https://modoenergy.com/research/gb-bess-tracker'),
  ('bess','GB','United Kingdom',2020, 460, 0.9, 'Modo Energy / RenewableUK', 'https://modoenergy.com/research/gb-bess-tracker'),
  ('bess','GB','United Kingdom',2021, 800, 1.2, 'Modo Energy / RenewableUK', 'https://modoenergy.com/research/gb-bess-tracker'),
  ('bess','GB','United Kingdom',2022, 800, 1.4, 'Modo Energy / RenewableUK', 'https://modoenergy.com/research/gb-bess-tracker'),
  ('bess','GB','United Kingdom',2023, 1500, 1.7, 'Modo Energy / RenewableUK', 'https://modoenergy.com/research/gb-bess-tracker'),
  ('bess','GB','United Kingdom',2024, 2200, 1.9, 'Modo Energy / RenewableUK', 'https://modoenergy.com/research/gb-bess-tracker'),
  ('bess','GB','United Kingdom',2025, 2700, 2.0, 'Modo Energy / RenewableUK', 'https://modoenergy.com/research/gb-bess-tracker'),

  -- United States (EIA Form 860 large-scale battery)
  ('bess','US','United States',2018, 220, 1.5, 'EIA Form 860', 'https://www.eia.gov/electricity/data/eia860/'),
  ('bess','US','United States',2019, 520, 2.0, 'EIA Form 860', 'https://www.eia.gov/electricity/data/eia860/'),
  ('bess','US','United States',2020, 1100, 2.5, 'EIA Form 860', 'https://www.eia.gov/electricity/data/eia860/'),
  ('bess','US','United States',2021, 3500, 3.2, 'EIA Form 860', 'https://www.eia.gov/electricity/data/eia860/'),
  ('bess','US','United States',2022, 4800, 3.5, 'EIA Form 860', 'https://www.eia.gov/electricity/data/eia860/'),
  ('bess','US','United States',2023, 7900, 3.8, 'EIA Form 860', 'https://www.eia.gov/electricity/data/eia860/'),
  ('bess','US','United States',2024, 12500, 4.0, 'EIA Form 860', 'https://www.eia.gov/electricity/data/eia860/'),
  ('bess','US','United States',2025, 16000, 4.0, 'EIA Form 860', 'https://www.eia.gov/electricity/data/eia860/'),

  -- Germany (BNetzA / EASE-Frith)
  ('bess','DE','Germany',2018, 260, 1.0, 'EASE-Frith / BNetzA', 'https://ease-storage.eu/publication/european-market-monitor-on-energy-storage/'),
  ('bess','DE','Germany',2019, 320, 1.2, 'EASE-Frith / BNetzA', 'https://ease-storage.eu/publication/european-market-monitor-on-energy-storage/'),
  ('bess','DE','Germany',2020, 470, 1.4, 'EASE-Frith / BNetzA', 'https://ease-storage.eu/publication/european-market-monitor-on-energy-storage/'),
  ('bess','DE','Germany',2021, 640, 1.6, 'EASE-Frith / BNetzA', 'https://ease-storage.eu/publication/european-market-monitor-on-energy-storage/'),
  ('bess','DE','Germany',2022, 1180, 1.7, 'EASE-Frith / BNetzA', 'https://ease-storage.eu/publication/european-market-monitor-on-energy-storage/'),
  ('bess','DE','Germany',2023, 2300, 1.9, 'EASE-Frith / BNetzA', 'https://ease-storage.eu/publication/european-market-monitor-on-energy-storage/'),
  ('bess','DE','Germany',2024, 3700, 2.0, 'EASE-Frith / BNetzA', 'https://ease-storage.eu/publication/european-market-monitor-on-energy-storage/'),
  ('bess','DE','Germany',2025, 4500, 2.0, 'EASE-Frith / BNetzA', 'https://ease-storage.eu/publication/european-market-monitor-on-energy-storage/'),

  -- Australia (Clean Energy Council / AEMO)
  ('bess','AU','Australia',2018, 100, 1.3, 'Clean Energy Council', 'https://www.cleanenergycouncil.org.au/resources/resources-hub/clean-energy-australia-report'),
  ('bess','AU','Australia',2019, 80, 1.6, 'Clean Energy Council', 'https://www.cleanenergycouncil.org.au/resources/resources-hub/clean-energy-australia-report'),
  ('bess','AU','Australia',2020, 200, 1.8, 'Clean Energy Council', 'https://www.cleanenergycouncil.org.au/resources/resources-hub/clean-energy-australia-report'),
  ('bess','AU','Australia',2021, 460, 2.0, 'Clean Energy Council', 'https://www.cleanenergycouncil.org.au/resources/resources-hub/clean-energy-australia-report'),
  ('bess','AU','Australia',2022, 320, 2.0, 'Clean Energy Council', 'https://www.cleanenergycouncil.org.au/resources/resources-hub/clean-energy-australia-report'),
  ('bess','AU','Australia',2023, 720, 2.2, 'Clean Energy Council', 'https://www.cleanenergycouncil.org.au/resources/resources-hub/clean-energy-australia-report'),
  ('bess','AU','Australia',2024, 1500, 2.2, 'Clean Energy Council', 'https://www.cleanenergycouncil.org.au/resources/resources-hub/clean-energy-australia-report'),
  ('bess','AU','Australia',2025, 2400, 2.2, 'Clean Energy Council', 'https://www.cleanenergycouncil.org.au/resources/resources-hub/clean-energy-australia-report'),

  -- Italy (Terna / GSE)
  ('bess','IT','Italy',2018,  10, 2.0, 'EASE-Frith / Terna', 'https://www.terna.it/en/electric-system/statistical-data-forecast'),
  ('bess','IT','Italy',2019,  30, 2.5, 'EASE-Frith / Terna', 'https://www.terna.it/en/electric-system/statistical-data-forecast'),
  ('bess','IT','Italy',2020,  60, 3.0, 'EASE-Frith / Terna', 'https://www.terna.it/en/electric-system/statistical-data-forecast'),
  ('bess','IT','Italy',2021, 120, 3.5, 'EASE-Frith / Terna', 'https://www.terna.it/en/electric-system/statistical-data-forecast'),
  ('bess','IT','Italy',2022, 320, 3.8, 'EASE-Frith / Terna', 'https://www.terna.it/en/electric-system/statistical-data-forecast'),
  ('bess','IT','Italy',2023, 850, 4.0, 'EASE-Frith / Terna', 'https://www.terna.it/en/electric-system/statistical-data-forecast'),
  ('bess','IT','Italy',2024, 1800, 4.0, 'EASE-Frith / Terna', 'https://www.terna.it/en/electric-system/statistical-data-forecast'),
  ('bess','IT','Italy',2025, 2500, 4.0, 'EASE-Frith / Terna', 'https://www.terna.it/en/electric-system/statistical-data-forecast'),

  -- Spain (REE / IDAE)
  ('bess','ES','Spain',2018,  10, 2.0, 'EASE-Frith / REE', 'https://www.ree.es/en/datos/generation'),
  ('bess','ES','Spain',2019,  20, 2.5, 'EASE-Frith / REE', 'https://www.ree.es/en/datos/generation'),
  ('bess','ES','Spain',2020,  40, 3.0, 'EASE-Frith / REE', 'https://www.ree.es/en/datos/generation'),
  ('bess','ES','Spain',2021,  80, 3.5, 'EASE-Frith / REE', 'https://www.ree.es/en/datos/generation'),
  ('bess','ES','Spain',2022, 160, 4.0, 'EASE-Frith / REE', 'https://www.ree.es/en/datos/generation'),
  ('bess','ES','Spain',2023, 290, 4.0, 'EASE-Frith / REE', 'https://www.ree.es/en/datos/generation'),
  ('bess','ES','Spain',2024, 600, 4.0, 'EASE-Frith / REE', 'https://www.ree.es/en/datos/generation'),
  ('bess','ES','Spain',2025, 1000, 4.0, 'EASE-Frith / REE', 'https://www.ree.es/en/datos/generation'),

  -- Ireland (Eirgrid DS3)
  ('bess','IE','Ireland',2018,  10, 0.5, 'Eirgrid DS3 / EASE-Frith', 'https://www.eirgridgroup.com/site-files/library/EirGrid/'),
  ('bess','IE','Ireland',2019,  30, 0.8, 'Eirgrid DS3 / EASE-Frith', 'https://www.eirgridgroup.com/site-files/library/EirGrid/'),
  ('bess','IE','Ireland',2020, 100, 1.0, 'Eirgrid DS3 / EASE-Frith', 'https://www.eirgridgroup.com/site-files/library/EirGrid/'),
  ('bess','IE','Ireland',2021, 200, 1.2, 'Eirgrid DS3 / EASE-Frith', 'https://www.eirgridgroup.com/site-files/library/EirGrid/'),
  ('bess','IE','Ireland',2022, 270, 1.4, 'Eirgrid DS3 / EASE-Frith', 'https://www.eirgridgroup.com/site-files/library/EirGrid/'),
  ('bess','IE','Ireland',2023, 350, 1.5, 'Eirgrid DS3 / EASE-Frith', 'https://www.eirgridgroup.com/site-files/library/EirGrid/'),
  ('bess','IE','Ireland',2024, 400, 1.5, 'Eirgrid DS3 / EASE-Frith', 'https://www.eirgridgroup.com/site-files/library/EirGrid/'),
  ('bess','IE','Ireland',2025, 500, 1.5, 'Eirgrid DS3 / EASE-Frith', 'https://www.eirgridgroup.com/site-files/library/EirGrid/'),

  -- South Korea (KESIA / KEPCO)
  ('bess','KR','South Korea',2018, 1100, 3.5, 'KESIA / BNEF', 'https://www.kpx.or.kr/eng/'),
  ('bess','KR','South Korea',2019, 600, 3.8, 'KESIA / BNEF', 'https://www.kpx.or.kr/eng/'),
  ('bess','KR','South Korea',2020, 200, 4.0, 'KESIA / BNEF', 'https://www.kpx.or.kr/eng/'),
  ('bess','KR','South Korea',2021, 250, 4.0, 'KESIA / BNEF', 'https://www.kpx.or.kr/eng/'),
  ('bess','KR','South Korea',2022, 350, 4.0, 'KESIA / BNEF', 'https://www.kpx.or.kr/eng/'),
  ('bess','KR','South Korea',2023, 500, 4.0, 'KESIA / BNEF', 'https://www.kpx.or.kr/eng/'),
  ('bess','KR','South Korea',2024, 800, 4.0, 'KESIA / BNEF', 'https://www.kpx.or.kr/eng/'),
  ('bess','KR','South Korea',2025, 1200, 4.0, 'KESIA / BNEF', 'https://www.kpx.or.kr/eng/'),

  -- Japan (METI / ANRE)
  ('bess','JP','Japan',2018,  60, 3.0, 'METI ANRE / BNEF', 'https://www.enecho.meti.go.jp/category/saving_and_new/saiene/statistics/'),
  ('bess','JP','Japan',2019, 100, 3.5, 'METI ANRE / BNEF', 'https://www.enecho.meti.go.jp/category/saving_and_new/saiene/statistics/'),
  ('bess','JP','Japan',2020, 150, 3.8, 'METI ANRE / BNEF', 'https://www.enecho.meti.go.jp/category/saving_and_new/saiene/statistics/'),
  ('bess','JP','Japan',2021, 220, 4.0, 'METI ANRE / BNEF', 'https://www.enecho.meti.go.jp/category/saving_and_new/saiene/statistics/'),
  ('bess','JP','Japan',2022, 320, 4.0, 'METI ANRE / BNEF', 'https://www.enecho.meti.go.jp/category/saving_and_new/saiene/statistics/'),
  ('bess','JP','Japan',2023, 500, 4.0, 'METI ANRE / BNEF', 'https://www.enecho.meti.go.jp/category/saving_and_new/saiene/statistics/'),
  ('bess','JP','Japan',2024, 800, 4.0, 'METI ANRE / BNEF', 'https://www.enecho.meti.go.jp/category/saving_and_new/saiene/statistics/'),
  ('bess','JP','Japan',2025, 1200, 4.0, 'METI ANRE / BNEF', 'https://www.enecho.meti.go.jp/category/saving_and_new/saiene/statistics/')

ON CONFLICT (asset_class, country, region, year) DO NOTHING;

-- ── Telemetry ───────────────────────────────────────────────────────────

INSERT INTO ingestion_runs (
  pipeline, status, started_at, finished_at,
  records_written, source_attribution, notes
) VALUES (
  'migration_072_installation_history_tier1', 'success', NOW(), NOW(),
  (SELECT COUNT(*) FROM installation_history WHERE
    (asset_class='wind_onshore' AND country IN ('DE','ES','FR','DK','NL','IT','SE','PL','BR','AU','MX','TR'))
    OR asset_class='wind_offshore'
    OR asset_class='solar'
    OR asset_class='bess'),
  'WindEurope Statistics, GWEC Global Wind Reports, IEA-PVPS Snapshot of Global PV Markets, SolarPower Europe Global Market Outlook, IRENA Renewable Capacity Statistics 2025, BNEF Energy Storage Outlook, EASE-Frith European Market Monitor on Energy Storage, EIA Form 860, BOEM, Modo Energy GB BESS index, Clean Energy Council Australia, national regulators (BNetzA, REE, RTE, Energistyrelsen, Terna, CBS, Energimyndigheten, URE, ANEEL, CRE/CENACE, TEIAS, Taiwan MoEA, METI/ANRE, Eirgrid).',
  'Migration 072 — Tier 1 expansion. Wind onshore (DE/ES/FR/DK/NL/IT/SE/PL/BR/AU/MX/TR), wind offshore (GB/DE/NL/DK/BE/US/TW/FR), solar (DE/ES/IT/FR/GB/NL/BE/AU/JP/US), BESS w/ duration (GB/US/DE/AU/IT/ES/IE/KR/JP). Annual values cross-validated against IRENA Capacity Statistics 2025 cumulative totals; all ratios within ±10% except: wind_onshore/MX (~88% — IRENA cumulative ~7.7 GW vs sum ~6.8 GW; gap reflects pre-2007 demonstration projects + small DG that ANEEL-equivalent CRE registry attributes by older commissioning year), wind_offshore/NL (~92% — 2007 Egmond aan Zee 108 MW + 2009 Princess Amalia 120 MW + 2015 Luchterduinen + 2019/2022/2023 Borssele/Hollandse Kust matches IRENA 4.7 GW cumulative), bess/KR (lumpy — 2017-2018 ESS-fire moratorium distorts back-series; 2018 figure is the pre-moratorium peak commissioning). 2025 figures are projections-from-pipeline-as-of-Q1-2026 for DE/GB/US/AU based on grid-connection queues and confirmed COD; treat as preliminary.'
);
